# Iris Flower Prediction 

# 1. importing all basic libaries

In [34]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

from sklearn.metrics import (r2_score, accuracy_score, precision_score, 
                           recall_score, f1_score)

# 2. data loading and refining

In [35]:
iris_df = pd.read_csv("iris.csv")

iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [36]:
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [37]:
#Mapping the speices
iris_df["Species"] = iris_df["Species"].map({"Iris-setosa" : 0,
                                             "Iris-versicolor" :1,
                                             "Iris-virginica": 2
                                             })


iris_df

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

# 3. Train Test Split

In [38]:
X = iris_df.drop(columns= ["Species" , "Id"])
Y = iris_df["Species"]

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.20, random_state=42
)

print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")
print(f"Number of features: {X_train.shape[1]}")

Training set size: 120 samples
Testing set size: 30 samples
Number of features: 4

# 3. Training data on logistic reg

In [40]:
from sklearn .linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    random_state=10,
    solver='lbfgs'  
).fit(X_train, Y_train)

In [41]:
Y_predict = log_model.predict(X_test)

#calculate metrics
print(f"Accuracy: {accuracy_score(Y_test, Y_predict)*100:.2f}%")
print(f"Precision: {precision_score(Y_test, Y_predict,average='micro')*100:.2f}%")
print(f"Recall: {recall_score(Y_test, Y_predict,average='micro')*100:.2f}%")
print(f"F1-Score: {f1_score(Y_test, Y_predict,average='micro')*100:.2f}%")
print(f"R2 Score: {r2_score(Y_test, Y_predict):.4f}")

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
F1-Score: 100.00%
R2 Score: 1.0000

# 4.Training data on Navie bayes

In [42]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB().fit(X_train, Y_train)

Y_pred = gnb.predict(X_test)

#calculate metrics
print(f"Accuracy: {accuracy_score(Y_test, Y_pred)*100:.2f}%")
print(f"Precision: {precision_score(Y_test, Y_pred,average='micro')*100:.2f}%")
print(f"Recall: {recall_score(Y_test, Y_pred,average='micro')*100:.2f}%")
print(f"F1-Score: {f1_score(Y_test, Y_pred,average='micro')*100:.2f}%")
print(f"R2 Score: {r2_score(Y_test, Y_pred):.4f}")

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
F1-Score: 100.00%
R2 Score: 1.0000

# 5. Training data on KNN

In [48]:
from sklearn.neighbors import KNeighborsClassifier

KNN = KNeighborsClassifier(n_neighbors=3).fit(X_train, Y_train)

Y_prediction = KNN.predict(X_test)

#calculate metrics
print(f"Accuracy: {accuracy_score(Y_test, Y_prediction)*100:.2f}%")
print(f"Precision: {precision_score(Y_test, Y_prediction,average='micro')*100:.2f}%")
print(f"Recall: {recall_score(Y_test, Y_prediction,average='micro')*100:.2f}%")
print(f"F1-Score: {f1_score(Y_test, Y_prediction,average='micro')*100:.2f}%")
print(f"R2 Score: {r2_score(Y_test, Y_prediction):.4f}")

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
F1-Score: 100.00%
R2 Score: 1.0000